# Generated by Django 3.0.8 on 2020-07-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='high_res',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
