# Generated by Django 3.0.8 on 2020-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_high_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='high_res',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
