# Generated by Django 3.0.8 on 2020-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200729_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('ICON', 'Icon'), ('LOGO', 'Logo'), ('POSTER', 'Poster')], max_length=15, null=True),
        ),
    ]
